### ISSUE TITLE
About update of variable obs_temp and death_temp

### ISSUE THREAD

**Issue by weiWANG881108** [shaman-lab/Counterfactual#1]
Very sorry to trouble you. I have a question about your code. In the script infer.m, you update the variable obs_temp and death_temp twice each time. One is updated with dailyIr_prior, dailyIu_prior and the other one is dailyIr_post, dailyIu_post. Why?

Thank you so much for your response

**Comment by shaman-lab** [comment]
Dear Wei Wang,

Thank you for pointing this out--this is an error in the code.  We are working to re-fit the model and re-do the analyses.

**Comment by SenPei-CU** [comment]
The bug is fixed and we have re-fit the model and re-done the analysis.
