### ISSUE TITLE
C++ code distribution to S, E, Iu, and R

### ISSUE THREAD

**Issue by mbhurley1958** [shaman-lab/Counterfactual#2]
I'm working through your package to try and extend it to evacuations for natural disasters. I'm trying to follow the operations in model_eakf.cpp. I'm a bit confused by the lines 168:177 below

    //comput IrD,IuD,SD,ED,RD
    for (i=0; i<num_loc; i++){
        for (j=part[i]; j<part[i+1]; j++){
            IrD[i]=IrD[i]+Ir[j];
            IuD[(int)nl[j]]=IuD[(int)nl[j]]+Iu[j];
            SD[i]=SD[i]+S[j];
            ED[i]=ED[i]+E[j];
            RD[i]=RD[i]+R[j];
        }
    }

I assume that IuD is redistributing commuting sub populations to their destination counties for the day and that IrD is remaining within the county and not commuting. I would expect that SD, ED, and RD would be redistributed like IuD, but they are redistributed like IrD. The night version has redistribution within the county, as I would expect.

What is the correct interpretation here or is this a bug?

**Comment by SenPei-CU** [comment]
Hi,

Thank you for spotting this bug. Yes. The day time population for SD, ED and RD should be computed like IuD. Now We have corrected it and uploaded the new version. We don't expect it will affect the results much as they are only used to compute inter-county random movement and there should not be much difference from the correct numbers. We will re-run everything during paper revision.

Thanks!
